import type { AgentDefinition } from "@vibefix/schemas";

/**
 * Full agent roster (Idea.txt MVP + verification pool). Pools, phases and the
 * UI graph all derive from this table.
 */
export const AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    agentId: "cartographer",
    role: "Maps the codebase: languages, frameworks, entrypoints, dependency graph",
    label: "Cartographer",
    phase: "recon",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["knowledge-graph"],
    consumes: [],
    runsInPool: "recon",
    freshContext: false,
  },
  {
    agentId: "historian",
    role: "Infers product intent from git history, README, and debt markers",
    label: "Historian",
    phase: "recon",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["product-intent"],
    consumes: [],
    runsInPool: "recon",
    freshContext: false,
  },
  {
    agentId: "test-surveyor",
    role: "Determines what safety net exists: frameworks, coverage, can it build/test",
    label: "Test Surveyor",
    phase: "recon",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["test-survey"],
    consumes: [],
    runsInPool: "recon",
    freshContext: false,
  },
  {
    agentId: "smell-detector",
    role: "Function/class-level smells: duplication, long functions, dead code",
    label: "Smell Detector",
    phase: "diagnosis",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["findings"],
    consumes: ["knowledge-graph", "test-survey", "product-intent"],
    runsInPool: "diagnosis",
    freshContext: false,
  },
  {
    agentId: "arch-auditor",
    role: "Architecture violations: cycles, god modules, missing boundaries",
    label: "Architecture Auditor",
    phase: "diagnosis",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["findings"],
    consumes: ["knowledge-graph", "test-survey", "product-intent"],
    runsInPool: "diagnosis",
    freshContext: false,
  },
  {
    agentId: "consistency-sentinel",
    role: "Style and convention drift: mixed patterns, naming, error handling",
    label: "Consistency Sentinel",
    phase: "diagnosis",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["findings"],
    consumes: ["knowledge-graph"],
    runsInPool: "diagnosis",
    freshContext: false,
  },
  {
    agentId: "security-agent",
    role: "Read-only security scan: secrets, injection sinks, sensitive logging",
    label: "Security",
    phase: "diagnosis",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["findings"],
    consumes: ["knowledge-graph"],
    runsInPool: "diagnosis",
    freshContext: false,
  },
  {
    agentId: "risk-assessor",
    role: "The pessimist: risk-scores every finding, declares do-not-touch zones",
    label: "Risk Assessor",
    phase: "riskAssessment",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["risk-assessments"],
    consumes: ["findings", "test-survey", "product-intent"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "synthesis",
    role: "Chief Diagnostician: merges findings into the prioritized Remediation Backlog",
    label: "Synthesis",
    phase: "synthesis",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["backlog"],
    consumes: ["findings", "risk-assessments", "knowledge-graph", "test-survey", "product-intent"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "minimality",
    role: "Anti-overengineering gate: shrinks scope, defers ambitious changes",
    label: "Minimality",
    phase: "minimality",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["backlog"],
    consumes: ["backlog", "product-intent"],
    runsInPool: null,
    freshContext: true,
  },
  {
    agentId: "harness-builder",
    role: "Pins current behavior: characterization plan + behavioral baseline",
    label: "Harness Builder",
    phase: "harness",
    capability: "TextGeneration",
    permission: "evidence-write",
    produces: ["characterization-plan", "behavioral-baseline"],
    consumes: ["backlog", "knowledge-graph", "test-survey"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "engineer",
    role: "The ONLY writer: implements one proposal per attempt inside a firewalled worktree",
    label: "Refactoring Engineer",
    phase: "execution",
    capability: "TextGeneration",
    permission: "worktree-write",
    produces: ["change-attempt"],
    consumes: ["backlog", "characterization-plan", "behavioral-baseline", "knowledge-graph", "product-intent"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "verifier",
    role: "Behavior Equivalence Verifier: deterministic gates + fresh-context adjudication",
    label: "Behavior Verifier",
    phase: "verification",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["verdict"],
    consumes: ["behavioral-baseline", "backlog"],
    runsInPool: "verification",
    freshContext: true,
    gateOrder: 1,
  },
  {
    agentId: "principle-reviewer",
    role: "Devil's advocate: does the diff follow the principle and stay minimal?",
    label: "Principle Reviewer",
    phase: "verification",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["verdict"],
    consumes: ["backlog"],
    runsInPool: "verification",
    freshContext: true,
    gateOrder: 2,
  },
  {
    agentId: "regression-sentinel",
    role: "Runs build, typecheck, lint, tests; blocks forbidden-zone touches",
    label: "Regression Sentinel",
    phase: "verification",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["verdict"],
    consumes: ["behavioral-baseline", "backlog"],
    runsInPool: "verification",
    freshContext: true,
    gateOrder: 3,
  },
  {
    agentId: "docent",
    role: "Explains everything: state of codebase, per-change rationale, what did NOT change",
    label: "Docent",
    phase: "report",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["report"],
    consumes: ["knowledge-graph", "test-survey", "findings", "backlog", "verdict", "product-intent"],
    runsInPool: null,
    freshContext: false,
  },
];

export function definitionFor(agentId: string): AgentDefinition {
  const def = AGENT_DEFINITIONS.find((d) => d.agentId === agentId);
  if (!def) throw new Error(`unknown agent definition '${agentId}'`);
  return def;
}
