import type { AgentDefinition } from "@vibefix/schemas";

/**
 * The 10 MVP agent definitions. Pools, phases and the UI graph all derive
 * from this table — adding a future agent (Historian, Security, Minimality,
 * Principle Reviewer, Regression Sentinel) is one more entry + implementation.
 */
export const AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    agentId: "cartographer",
    role: "Maps the codebase: languages, frameworks, entrypoints, dependency graph",
    label: "Cartographer",
    phase: "recon",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["knowledge-graph"],
    consumes: [],
    runsInPool: "recon",
    freshContext: false,
  },
  {
    agentId: "test-surveyor",
    role: "Determines what safety net exists: frameworks, coverage, can it build/test",
    label: "Test Surveyor",
    phase: "recon",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["test-survey"],
    consumes: [],
    runsInPool: "recon",
    freshContext: false,
  },
  {
    agentId: "smell-detector",
    role: "Function/class-level smells: duplication, long functions, dead code",
    label: "Smell Detector",
    phase: "diagnosis",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["findings"],
    consumes: ["knowledge-graph", "test-survey"],
    runsInPool: "diagnosis",
    freshContext: false,
  },
  {
    agentId: "arch-auditor",
    role: "Architecture violations: cycles, god modules, missing boundaries",
    label: "Architecture Auditor",
    phase: "diagnosis",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["findings"],
    consumes: ["knowledge-graph", "test-survey"],
    runsInPool: "diagnosis",
    freshContext: false,
  },
  {
    agentId: "risk-assessor",
    role: "The pessimist: risk-scores every finding, declares do-not-touch zones",
    label: "Risk Assessor",
    phase: "riskAssessment",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["risk-assessments"],
    consumes: ["findings", "test-survey"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "synthesis",
    role: "Chief Diagnostician: merges findings into the prioritized Remediation Backlog",
    label: "Synthesis",
    phase: "synthesis",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["backlog"],
    consumes: ["findings", "risk-assessments", "knowledge-graph", "test-survey"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "harness-builder",
    role: "Pins current behavior: characterization plan + behavioral baseline",
    label: "Harness Builder",
    phase: "harness",
    capability: "TextGeneration",
    permission: "evidence-write",
    produces: ["characterization-plan", "behavioral-baseline"],
    consumes: ["backlog", "knowledge-graph", "test-survey"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "engineer",
    role: "The ONLY writer: implements one proposal per attempt inside a firewalled worktree",
    label: "Refactoring Engineer",
    phase: "execution",
    capability: "TextGeneration",
    permission: "worktree-write",
    produces: ["change-attempt"],
    consumes: ["backlog", "characterization-plan", "behavioral-baseline", "knowledge-graph"],
    runsInPool: null,
    freshContext: false,
  },
  {
    agentId: "verifier",
    role: "Behavior Equivalence Verifier: deterministic gates + fresh-context adjudication",
    label: "Behavior Verifier",
    phase: "verification",
    capability: "TypedDecision",
    permission: "read-only",
    produces: ["verdict"],
    consumes: ["behavioral-baseline", "backlog"],
    runsInPool: null,
    freshContext: true,
  },
  {
    agentId: "docent",
    role: "Explains everything: state of codebase, per-change rationale, what did NOT change",
    label: "Docent",
    phase: "report",
    capability: "TextGeneration",
    permission: "read-only",
    produces: ["report"],
    consumes: ["knowledge-graph", "test-survey", "findings", "backlog", "verdict"],
    runsInPool: null,
    freshContext: false,
  },
];

export function definitionFor(agentId: string): AgentDefinition {
  const def = AGENT_DEFINITIONS.find((d) => d.agentId === agentId);
  if (!def) throw new Error(`unknown agent definition '${agentId}'`);
  return def;
}
